### ISSUE TITLE
Crash with java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rnauber** [sungbin5304/SimpleCodeEditor#1]
First of all, thank you  @sungbin5304 for creating this great piece of software! I am starting to integrate it in my little app (https://github.com/rnauber/ESPHomeRC) as an interactive editor for java script.
It works and looks great, however, after some seconds of editing, it crashes:

`
2021-01-18 00:28:18.046 16493-16493/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.nauber.esphomerc, PID: 16493
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:984)
        at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:988)
        at android.text.SpannableStringBuilder.getSpans(SpannableStringBuilder.java:877)
        at android.text.SpannableStringBuilder.getSpans(SpannableStringBuilder.java:847)
        at android.text.SpanSet.init(SpanSet.java:47)
        at android.text.TextLine.handleRun(TextLine.java:1135)
        at android.text.TextLine.drawRun(TextLine.java:512)
        at android.text.TextLine.draw(TextLine.java:244)
        at android.text.Layout.drawText(Layout.java:581)
        at android.widget.Editor.drawHardwareAcceleratedInner(Editor.java:2119)
        at android.widget.Editor.drawHardwareAccelerated(Editor.java:2038)
        at android.widget.Editor.onDraw(Editor.java:1978)
        at android.widget.TextView.onDraw(TextView.java:8096)
        at com.sungbin.texteditor.library.SimpleCodeEditor.onDraw(SimpleCodeEditor.kt:185)
        at android.view.View.draw(View.java:21879)
        at android.view.View.updateDisplayListIfDirty(View.java:20752)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20707)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20707)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20707)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20707)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20707)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20707)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20707)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20707)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20707)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20707)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:725)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:731)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:840)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4035)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3799)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3095)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1958)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8636)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
        at android.view.Choreographer.doCallbacks(Choreographer.java:765)
        at android.view.Choreographer.doFrame(Choreographer.java:700)
2021-01-18 00:28:18.047 16493-16493/? E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7156)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
2021-01-18 00:28:18.056 3042-3523/? D/Debug: !@DumpState : SHIP
2021-01-18 00:28:18.056 3042-3523/? D/Debug: !@DumpState : debug level:0x4f4c
2021-01-18 00:28:18.056 3042-3523/? D/Debug: !@Dumpstate : Finally, system will skip dumpstate
2021-01-18 00:28:18.056 3042-3523/? W/ActivityManager: crash : dev.nauber.esphomerc,0
2021-01-18 00:28:18.059 3042-3523/? W/ActivityManager:   Force finishing activity dev.nauber.esphomerc/.MainActivity
`

What can I do to debug this further?

Thank you,
Richard

**Comment by rnauber** [comment]
Just a screenshot of my use case:
![image](https://user-images.githubusercontent.com/7414650/104859832-36ed0900-5928-11eb-9748-84bccc216c1a.png)

**Comment by sungbin5304** [comment]
I am trying to fix this bug.
Thank you for the bug issue.

**Comment by rnauber** [comment]
I have tried commit 63451a2 and it seems that the problem occurs more seldom. 
But once in a while, I still get:

```
2021-01-29 21:22:23.727 26900-26900/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.nauber.esphomerc, PID: 26900
    java.lang.ArrayIndexOutOfBoundsException: length=15; index=15
        at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:984)
        at android.text.SpannableStringBuilder.getSpans(SpannableStringBuilder.java:877)
        at android.text.SpannableStringBuilder.getSpans(SpannableStringBuilder.java:847)
        at android.text.SpannableStringBuilder.equals(SpannableStringBuilder.java:1604)
        at android.widget.TextView.notifyAutoFillManagerAfterTextChangedIfNeeded(TextView.java:10969)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:10952)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:14155)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1273)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:576)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:506)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:36)
        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:849)
        at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:199)
        at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:341)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7179)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```


Thank you!
